version: '3.5'

services:
  symfony_skeleton:
    container_name: symfony_skeleton
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=symfony_skeleton
    ports:
      - '1000:8000'
    networks:
      - symfony_skeleton-network
    depends_on:
      - symfony_skeleton-postgres

  symfony_skeleton-postgres:
    container_name: symfony_skeleton-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: symfony_skeleton
    volumes:
      - symfony_skeleton-postgres-pgsql-data:/var/lib/postgresql/data:rw
    networks:
      - symfony_skeleton-network

networks:
  symfony_skeleton-network:

volumes:
  symfony_skeleton-postgres-pgsql-data:
